# Generated by Django 3.2.12 on 2024-03-31 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_items',
            new_name='products',
        ),
    ]
