# Generated by Django 3.2.12 on 2024-04-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkapp', '0005_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='first_name', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='second_name',
            field=models.CharField(default='second_name', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='default_category', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=4),
        ),
    ]
