# Generated by Django 3.2.12 on 2024-04-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkapp', '0006_auto_20240415_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='черный', max_length=64),
            preserve_default=False,
        ),
    ]
